class CandidateModel {
  final String id;
  final String empId;
  final String name;
  final String projectName;
  final String subProjectName;
  final String designation;
  final String team;
  final String gender;
  final String heightInCm;
  final String email;
  final String shutterflyEmail;
  final int voteCount;

  const CandidateModel({
    required this.id,
    this.empId = '',
    required this.name,
    this.projectName = '',
    this.subProjectName = '',
    this.designation = '',
    this.team = '',
    this.gender = '',
    this.heightInCm = '',
    this.email = '',
    this.shutterflyEmail = '',
    this.voteCount = 0,
  });

  /// Gender-based avatar emoji.
  String get emoji =>
      gender == 'Female' ? '👩' : gender == 'Male' ? '👨' : '👤';

  CandidateModel copyWith({int? voteCount}) {
    return CandidateModel(
      id: id,
      empId: empId,
      name: name,
      projectName: projectName,
      subProjectName: subProjectName,
      designation: designation,
      team: team,
      gender: gender,
      heightInCm: heightInCm,
      email: email,
      shutterflyEmail: shutterflyEmail,
      voteCount: voteCount ?? this.voteCount,
    );
  }
}

/// Complete static candidate list derived from the resource sheet.
/// Columns: Emp ID, Name, Project Name, Sub Project Name, Designation,
/// Team, Gender, In Cm's, Email, Shutterfly Email ID  (T-shirt size excluded).
class VotingData {
  static List<CandidateModel> candidates = [
    CandidateModel(
      id: 'c1',
      empId: 'Client',
      name: 'Parveen Yadav',
      projectName: 'Shutterfly',
      designation: '',
      team: 'Sr.Director - Engineering',
      gender: 'Male',
    ),
    CandidateModel(
      id: 'c2',
      empId: '311170',
      name: 'Thumukuntla Bhargavi',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_QE',
      designation: 'Software Engineer - QA',
      team: 'Android',
      gender: 'Female',
      heightInCm: '40',
      email: 'BHARGAVI.THUMUKUNTLA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c3',
      empId: '311155',
      name: 'Uma Shankar Nori',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_QE',
      designation: 'Team Lead - QA',
      team: 'IOS',
      gender: 'Male',
      heightInCm: '40',
      email: 'UMASHANKAR.NORI@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c4',
      empId: '316603',
      name: 'Tumma Aruna Kumari',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_IOS',
      designation: 'Technical Lead - SD',
      team: 'IOS',
      gender: 'Female',
      email: 'ARUNA.TUMMA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c5',
      empId: '316597',
      name: 'Rakesh Rai',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_IOS',
      designation: 'Technical Lead',
      team: 'IOS',
      gender: 'Male',
      heightInCm: '40',
      email: 'RAKESH.RAI@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c6',
      empId: '315034',
      name: 'Sanku VikasTeja',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_Android',
      designation: 'Senior Analyst',
      team: 'Android',
      gender: 'Male',
      heightInCm: '42',
      email: 'VIKASTEJA.SANKU@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c7',
      empId: '302291',
      name: 'Bhaskar Reddy Thamma',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_QE',
      designation: 'Associate Director - QE',
      team: 'Global Delivery',
      gender: 'Male',
      heightInCm: '40',
      email: 'bhaskar.t@valuelabs.com',
    ),
    CandidateModel(
      id: 'c8',
      empId: '311197',
      name: 'Vyshnavadasu Lakshmi Narayana',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_Automation',
      designation: 'Senior Software Engineer - QE',
      team: 'Android',
      gender: 'Male',
      heightInCm: '39',
      email: 'LAKSHMINARAYANA.V@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c9',
      empId: '311410',
      name: 'Abdul Yasin',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_IOS',
      designation: 'Technical Lead',
      team: 'IOS',
      gender: 'Male',
      heightInCm: '42',
      email: 'YASIN.ABDUL@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c10',
      empId: '300269',
      name: 'Kiran Dandeboina',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App PMO',
      designation: 'Director - SD',
      team: 'Global Delivery',
      gender: 'Male',
      email: 'kiran.dandeboina@valuelabs.com',
    ),
    CandidateModel(
      id: 'c11',
      empId: '316447',
      name: 'Kalyani',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_IOS',
      designation: 'Technical Lead - SD',
      team: 'IOS',
      gender: 'Female',
      email: 'KALYANI@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c12',
      empId: '316561',
      name: 'Neeraj Yadav',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_Android',
      designation: 'Consultant',
      team: 'Android',
      gender: 'Male',
      heightInCm: '39',
      email: 'NEERAJ.YADAV@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c13',
      empId: '314805',
      name: 'Boddula Ramprasad',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App DevOps',
      designation: 'System Analyst - SD',
      team: 'DevOps',
      gender: 'Male',
      heightInCm: '41',
      email: 'RAMPRASAD.BODDULA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c14',
      empId: '311219',
      name: 'Sayyed Sameer Sayyed Nisar',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_Automation',
      designation: 'Analyst - QA',
      team: 'IOS',
      gender: 'Male',
      heightInCm: '48',
      email: 'sameer.syed@valuelabs.com',
    ),
    CandidateModel(
      id: 'c15',
      empId: '300488',
      name: 'Venkatesh Seerapu',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_Automation',
      designation: 'Associate Architect - SD',
      team: 'Quality Engineering',
      gender: 'Male',
      email: 'venkatesh.seerapu@valuelabs.com',
    ),
    CandidateModel(
      id: 'c16',
      empId: '310760',
      name: 'Srikanth Jessu',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_Android',
      designation: 'Sr. Technical Lead',
      team: 'Android',
      gender: 'Male',
      heightInCm: '40',
      email: 'SRIKANTH.JESSU@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c17',
      empId: '311119',
      name: 'Kosuri Padmaja',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_Automation',
      designation: 'Analyst - QA',
      team: 'Android',
      gender: 'Female',
      email: 'PADMAJA.KOSURI@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c18',
      empId: '311656',
      name: 'Srikuramdasu Satya Narasimha Nikhil',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_IOS',
      designation: 'Senior Software Engineer',
      team: 'IOS',
      gender: 'Male',
      email: 'NIKHIL.S@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c19',
      empId: '310774',
      name: 'Peddinti Simhachalam Naidu',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_IOS',
      designation: 'Architect',
      team: 'IOS',
      gender: 'Male',
      email: 'SIMHACHALAM.P@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c20',
      empId: '300370',
      name: 'Keshav Kota',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_QE',
      designation: 'Analyst - QA',
      team: 'Android',
      gender: 'Male',
      heightInCm: '39',
      email: 'keshav.kota@valuelabs.com',
    ),
    CandidateModel(
      id: 'c21',
      empId: '311074',
      name: 'Penmethsa Bhaskar Phani Varma',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_Automation',
      designation: 'Software Engineer - QA',
      team: 'IOS',
      gender: 'Male',
      heightInCm: '48',
      email: 'BHASKAR.PENMETHSA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c22',
      empId: '311814',
      name: 'Srinivas Achanta',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_QE',
      designation: 'Senior Software Engineer - QA',
      team: 'IOS',
      gender: 'Male',
      heightInCm: '46',
      email: 'srinivas.achanta@valuelabs.com',
    ),
    CandidateModel(
      id: 'c23',
      empId: '311793',
      name: 'Kotha Cherishma Reddy',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_Automation',
      designation: 'Sr. Software Engineer - QA',
      team: 'IOS',
      gender: 'Female',
      heightInCm: '42',
      email: 'CHERISHMA.KOTHA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c24',
      empId: '314750',
      name: 'Pushpendra Mahawar',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_Android',
      designation: 'Technical Lead - SD',
      team: 'Android',
      gender: 'Male',
      email: 'PUSHPENDRA.MAHAWAR@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c25',
      empId: '316444',
      name: 'Raj Kumar Singh',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_Android',
      designation: 'Technical Lead-SD',
      team: 'Android',
      gender: 'Male',
      email: 'RAJKUMAR.SINGH@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c26',
      empId: '314769',
      name: 'Ashutosh Kumar',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_Android',
      designation: 'Module Lead - SD',
      team: 'Android',
      gender: 'Male',
      email: 'ASHUTOSH.KUMAR@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c27',
      empId: '311242',
      name: 'Indrajitkumar VinodKumar Chavda',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_IOS',
      designation: 'Technical Lead',
      team: 'IOS',
      gender: 'Male',
      email: 'INDRAJIT.CHAVDA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c28',
      empId: '311160',
      name: 'Hareesh Podella',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_Automation',
      designation: 'Analyst - QA',
      team: 'Android',
      gender: 'Male',
      email: 'HAREESH.PODELLA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c29',
      empId: '311878',
      name: 'Thangellapally Shravani',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_QE',
      designation: 'Software Engineer - QE',
      team: 'IOS',
      gender: 'Female',
      heightInCm: '42',
      email: 'SHRAVANI.T@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c30',
      empId: '311433',
      name: 'Mounica Komaravalli',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_QE',
      designation: 'Team Lead - QA',
      team: 'Android',
      gender: 'Female',
      heightInCm: '42',
      email: 'MOUNICA.K@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c31',
      empId: '311079',
      name: 'Koushik Dutta',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_IOS',
      designation: 'Technical Lead',
      team: 'IOS',
      gender: 'Male',
      email: 'KOUSHIK.DUTTA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c32',
      empId: '316494',
      name: 'Subhash',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_IOS',
      designation: 'Associate Architect - SD',
      team: 'IOS',
      gender: 'Male',
      email: 'subhash.rana@valuelabs.com',
    ),
    CandidateModel(
      id: 'c33',
      empId: '316563',
      name: 'Naveen Kumar',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_IOS',
      designation: 'Consultant',
      team: 'IOS',
      gender: 'Male',
      email: 'NAVEEN.KUMAR1@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c34',
      empId: '314636',
      name: 'Laxmanamurthy Kandi',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_Android',
      designation: 'Technical Lead-SD',
      team: 'Android',
      gender: 'Male',
      email: 'LAXMANAMURTHY.K@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c35',
      empId: '311198',
      name: 'Prajna P Shiroor',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_QE',
      designation: 'Senior Software Engineer - QA',
      team: 'Android',
      gender: 'Female',
      heightInCm: '40',
      email: 'PRAJNA.SHIROOR@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c36',
      empId: '311678',
      name: 'Bagu Siva krishna',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App Dev_IOS',
      designation: 'Senior Analyst',
      team: 'IOS',
      gender: 'Male',
      email: 'SIVAKRISHNA.BAGU@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c37',
      empId: '313132',
      name: 'Spandana Sunkenapelly',
      projectName: 'TAG-Divya',
      subProjectName: 'TAG - Team',
      designation: 'Specialist - HR',
      team: 'Talent Acquisition',
      gender: 'Female',
      email: 'SPANDANA.S@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c38',
      empId: '312920',
      name: 'Sushanth Nayani',
      projectName: 'TAG-Divya',
      subProjectName: 'TAG - Team',
      designation: 'Specialist - HR',
      team: 'Talent Acquisition',
      gender: 'Male',
      email: 'SUSHANTH.NAYANI@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c39',
      empId: '312905',
      name: 'Rama Lakshmi Prasad',
      projectName: 'TAG-Divya',
      subProjectName: 'TAG - Team',
      designation: 'Manager - HR',
      team: 'Talent Acquisition',
      gender: 'Male',
      email: 'RAMALAKSHMI.PRASAD@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c40',
      empId: '312960',
      name: 'Shravan Kumar Mavurapu',
      projectName: 'TAG-Divya',
      subProjectName: 'TAG - Lead',
      designation: 'Associate Manager - HR',
      team: 'Talent Acquisition',
      gender: 'Male',
      email: 'SHRAVAN.M@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c41',
      empId: '316346',
      name: 'Alladu Venkata Sasi Kumar',
      projectName: 'TAG-Divya',
      subProjectName: 'TAG - Team',
      designation: 'Senior Executive',
      team: 'Talent Acquisition',
      gender: 'Male',
      email: 'SASIKUMAR.ALLADU@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c42',
      empId: '312904',
      name: 'Sumit Saha',
      projectName: 'Employee Success Organisation (ESO)',
      subProjectName: 'Employee Success Organisation (ESO)',
      designation: 'Senior Executive',
      team: 'ESO',
      gender: 'Male',
      email: 'SUMIT.SAHA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c43',
      empId: '312283',
      name: 'Susmitha Kuchibhotla',
      projectName: 'PlanSource',
      subProjectName: 'PlanSource - HR',
      designation: 'Assistant Director - HR',
      team: 'ESO',
      gender: 'Female',
      email: 'susmitha.kuchibhotla@valuelabs.com',
    ),
    CandidateModel(
      id: 'c44',
      empId: '312950',
      name: 'Bandaru Nirosha',
      projectName: 'TAG-Surendra',
      subProjectName: 'TAG - Team',
      designation: 'Senior Executive',
      team: 'Talent Acquisition',
      gender: 'Female',
      email: 'NIROSHA.BANDARU@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c45',
      empId: '315024',
      name: 'Syed Shakeel',
      projectName: 'Global Delivery-Divya',
      subProjectName: 'Global Delivery - Team',
      designation: 'Analyst',
      team: 'PMO',
      gender: 'Male',
      heightInCm: '46',
      email: 'SYED.SHAKEEL@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c46',
      empId: '300349',
      name: 'Kasi Viswanath Movva',
      projectName: 'Global Delivery-Divya',
      subProjectName: 'Global Delivery - Team',
      designation: 'SVP - Global Delivery',
      team: 'Global Delivery',
      gender: 'Male',
      email: 'kasi.movva@valuelabs.com',
    ),
    CandidateModel(
      id: 'c47',
      empId: '314457',
      name: 'Sai Divya Gummadi',
      projectName: 'Global Delivery-Divya',
      subProjectName: 'Global Delivery - Lead',
      designation: 'VP - PMO, Global Delivery',
      team: 'Global Delivery',
      gender: 'Female',
      email: 'divya.gummadi@valuelabs.com',
    ),
    CandidateModel(
      id: 'c48',
      name: 'Vikranth Kumar Reddy Katanguri',
      projectName: 'Tower Head',
      team: 'Global Delivery',
      gender: 'Male',
      email: 'security@valuelabs.com',
    ),
    CandidateModel(
      id: 'c49',
      empId: '314458',
      name: 'Udaya Narayan',
      projectName: 'Global Delivery-Divya',
      subProjectName: 'Global Delivery - Team',
      designation: 'Senior Specialist',
      team: 'PMO',
      gender: 'Female',
      email: 'UDAYA.N@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c50',
      empId: '740009',
      name: 'Venkata Usha Kiranmai Thammavarapu',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App PMO',
      designation: 'VP - Global Delivery',
      team: 'PMO',
      gender: 'Female',
      email: 'usha.tammavarapu@valuelabs.com',
    ),
    CandidateModel(
      id: 'c51',
      empId: '316614',
      name: 'Komal Nutan Das',
      team: 'IOS',
      gender: 'Female',
      email: 'KOMAL.DAS@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c52',
      empId: '316626',
      name: 'Dhiraj Kumar',
      team: 'IOS',
      gender: 'Male',
      email: 'DHIRAJ.KUMAR1@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c53',
      empId: '316627',
      name: 'Anurag Sharma',
      team: 'IOS',
      gender: 'Male',
      email: 'ANURAG.SHARMA1@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c54',
      empId: '312104',
      name: 'Ganta Venkata Rajesh Babu',
      projectName: 'Shutterfly',
      subProjectName: 'Mobile App_QE',
      team: 'IOS',
      gender: 'Male',
      heightInCm: '46',
      email: 'VENKATARAJESH.GANTA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c55',
      empId: '315614',
      name: 'Radha Rani Sahu',
      team: 'ESO',
      gender: 'Female',
      email: 'RADHARANI.SAHU@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c56',
      empId: '311682',
      name: 'Rama Krishna Reddy Sathi',
      projectName: 'Snapfish',
      team: 'IOS',
      gender: 'Male',
      email: 'RAMAKRISHNA.SATHI@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c57',
      empId: '310600',
      name: 'Sajal Jain',
      projectName: 'Snapfish',
      team: 'Android',
      gender: 'Male',
      heightInCm: '40',
      email: 'SAJAL.JAIN@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c58',
      empId: '302796',
      name: 'Srinivas Varada',
      projectName: 'Snapfish',
      team: 'IOS',
      gender: 'Male',
      heightInCm: '42',
      email: 'srinivas.varada@valuelabs.com',
    ),
    CandidateModel(
      id: 'c59',
      empId: '312129',
      name: 'P Yellappa',
      projectName: 'Snapfish',
      team: 'Android',
      gender: 'Male',
      heightInCm: '40',
      email: 'YELLAPPA.P@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c60',
      empId: '311678',
      name: 'Siva Krishna Bagu',
      projectName: 'Shutterfly',
      team: 'IOS',
      gender: 'Male',
      heightInCm: '40',
      email: 'SIVAKRISHNA.BAGU@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c61',
      empId: '305245',
      name: 'Uday Kumar Varri',
      projectName: 'Snapfish',
      team: 'IOS',
      gender: 'Male',
      heightInCm: '40',
      email: 'UDAY.VARRI@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c62',
      empId: '316041',
      name: 'Mujaffar Husen',
      projectName: 'Snapfish',
      team: 'Android',
      gender: 'Male',
      email: 'Mujaffar.husen@valuelabs.com',
    ),
    CandidateModel(
      id: 'c63',
      empId: '314295',
      name: 'Srikanth Mamidala',
      projectName: 'TAG-Ops',
      subProjectName: 'TAG-Ops',
      designation: 'Associate Manager - HR',
      team: 'Talent Acquisition',
      gender: 'Male',
      email: 'SRIKANTH.MAMIDALA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c64',
      empId: '800040',
      name: 'Bhanuchand Bandarupalli',
      projectName: 'Global PMO',
      subProjectName: 'Global PMO',
      designation: 'Director',
      team: 'Finance',
      gender: 'Male',
      email: 'BHANUCHAND.BANDARUPALLI@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c65',
      empId: '315916',
      name: 'Narendra Varma Raju Vegiraju',
      team: 'Finance',
      gender: 'Male',
      email: 'narendra.vegiraju@valuelabs.com',
    ),
    CandidateModel(
      id: 'c66',
      empId: '315184',
      name: 'Sairam Midde',
      team: 'Finance',
      gender: 'Male',
      email: 'sairam.midde@valuelabs.com',
    ),
    CandidateModel(
      id: 'c67',
      empId: '315910',
      name: 'Harsha Venkata Bhavani Putta',
      team: 'Finance',
      gender: 'Male',
      email: 'HARSHA.PUTTA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c68',
      empId: '316618',
      name: 'Amit Kumar Singh',
      team: 'IOS',
      gender: 'Male',
      email: 'AMITKUMAR.S@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c69',
      empId: '314996',
      name: 'Barigala Meghanath',
      team: 'Android',
      gender: 'Male',
      email: 'MEGHANATH.BARIGALA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c70',
      name: 'Jangla Suman',
      email: 'SUMAN.J@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c71',
      name: 'Raghavender Jeggari',
      email: 'RAGHAVENDER.JEGGARI@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c72',
      name: 'Aashish M Jethwani',
      email: 'aashish.jethwani@valuelabs.com',
    ),
    CandidateModel(
      id: 'c73',
      name: 'Kunubal Kant',
      email: 'KUNUBAL.KANT@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c74',
      name: 'Mansi Deshpande',
      email: 'MANSI.DESHPANDE@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c75',
      name: 'Gandla Likhitha',
      email: 'LIKHITHA.GANDLA@VALUELABS.COM',
    ),
    CandidateModel(
      id: 'c76',
      name: 'Goutam Reddy Poreddy',
      email: 'gowthamreddy.p@valuelabs.com',
    ),
    CandidateModel(
      id: 'c77',
      name: 'Nadigola Archana',
      email: 'ARCHANA.NADIGOLA@VALUELABS.COM',
    ),
  ];
}